/* eslint-disable */
// @ts-nocheck
// biome-ignore lint: disable
// oxlint-disable
// ------
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399

export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    Button: typeof import('./src/components/button/Button.vue')['default']
    Card: typeof import('./src/components/card/Card.vue')['default']
    CardAction: typeof import('./src/components/card/CardAction.vue')['default']
    CardContent: typeof import('./src/components/card/CardContent.vue')['default']
    CardDescription: typeof import('./src/components/card/CardDescription.vue')['default']
    CardFooter: typeof import('./src/components/card/CardFooter.vue')['default']
    CardHeader: typeof import('./src/components/card/CardHeader.vue')['default']
    CardTitle: typeof import('./src/components/card/CardTitle.vue')['default']
    Checkbox: typeof import('./src/components/checkbox/Checkbox.vue')['default']
    Display: typeof import('./src/components/app/display.vue')['default']
    Field: typeof import('./src/components/field/Field.vue')['default']
    FieldContent: typeof import('./src/components/field/FieldContent.vue')['default']
    FieldDescription: typeof import('./src/components/field/FieldDescription.vue')['default']
    FieldError: typeof import('./src/components/field/FieldError.vue')['default']
    FieldGroup: typeof import('./src/components/field/FieldGroup.vue')['default']
    FieldLabel: typeof import('./src/components/field/FieldLabel.vue')['default']
    FieldLegend: typeof import('./src/components/field/FieldLegend.vue')['default']
    FieldSeparator: typeof import('./src/components/field/FieldSeparator.vue')['default']
    FieldSet: typeof import('./src/components/field/FieldSet.vue')['default']
    FieldTitle: typeof import('./src/components/field/FieldTitle.vue')['default']
    Input: typeof import('./src/components/input/Input.vue')['default']
    InputGroup: typeof import('./src/components/input-group/InputGroup.vue')['default']
    InputGroupAddon: typeof import('./src/components/input-group/InputGroupAddon.vue')['default']
    InputGroupButton: typeof import('./src/components/input-group/InputGroupButton.vue')['default']
    InputGroupInput: typeof import('./src/components/input-group/InputGroupInput.vue')['default']
    InputGroupText: typeof import('./src/components/input-group/InputGroupText.vue')['default']
    InputGroupTextarea: typeof import('./src/components/input-group/InputGroupTextarea.vue')['default']
    Label: typeof import('./src/components/label/Label.vue')['default']
    RadioGroup: typeof import('./src/components/radio-group/RadioGroup.vue')['default']
    RadioGroupItem: typeof import('./src/components/radio-group/RadioGroupItem.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    Select: typeof import('./src/components/select/Select.vue')['default']
    SelectContent: typeof import('./src/components/select/SelectContent.vue')['default']
    SelectGroup: typeof import('./src/components/select/SelectGroup.vue')['default']
    SelectItem: typeof import('./src/components/select/SelectItem.vue')['default']
    SelectItemText: typeof import('./src/components/select/SelectItemText.vue')['default']
    SelectLabel: typeof import('./src/components/select/SelectLabel.vue')['default']
    SelectScrollDownButton: typeof import('./src/components/select/SelectScrollDownButton.vue')['default']
    SelectScrollUpButton: typeof import('./src/components/select/SelectScrollUpButton.vue')['default']
    SelectSeparator: typeof import('./src/components/select/SelectSeparator.vue')['default']
    SelectTrigger: typeof import('./src/components/select/SelectTrigger.vue')['default']
    SelectValue: typeof import('./src/components/select/SelectValue.vue')['default']
    Separator: typeof import('./src/components/separator/Separator.vue')['default']
    Sonner: typeof import('./src/components/sonner/Sonner.vue')['default']
    Switch: typeof import('./src/components/switch/Switch.vue')['default']
    Textarea: typeof import('./src/components/textarea/Textarea.vue')['default']
  }
}
